version: "2"
services:
  client:
    build: ./client/
    # image: react-nginx
    ports:
      - "8080:80"
    volumes:
      # - ./client:/app
      - ./client/public:/srv/www/static
    depends_on:
      - authserver
    links:
      - authserver
  authserver:
    build: ./authServer/
    ports:
      - "5555:5555"
    volumes:
      - ./authServer:/app
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  apiserver:
    build: ./apiServer/
    ports:
      - "4444:4444"
    volumes:
      - ./apiServer:/app
    depends_on:
      - mongodb
  socketserver:
    build: ./socketServer/
    ports:
      - "3456:3456"
    volumes:
      - ./socketServer:/app
    depends_on:
      - authserver
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8000:8080"
  #   volumes:
  #     - ./client/public:/srv/www/static
  # #     - ./proxy.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - client
  #     - authserver